@__HostAddress = http://localhost:5000


POST {{__HostAddress}}/api/payment/sepay-webhook
Content-Type: application/json

{
    "content": "GIAO DICH CHUYEN KHOAN ND BK123"
}

###

POST {{__HostAddress}}/api/payment/sepay-webhook
Content-Type: application/json

{
    "content": "GIAO DICH TRUNG LAP BK123"
}