services:
  db:
    image: postgres:16-alpine
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: booking_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Use this to log in
      PGADMIN_DEFAULT_PASSWORD: root         # Use this to log in
    ports:
      - "8081:80"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: booking_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: booking_api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data: